### ISSUE TITLE
Professor administration of groups

### ISSUE THREAD

**Issue by DannySager** [cse442-fall-2019-offering/442projects-django-mango#15]
As a professor who wants to view or modify groups I want to see the group hub from the professor perspective so I can administrate any group changes that need to take place to avoid conflict.

**Comment by bryanamoy** [comment]
Acceptance Test:
(1) Login website with professor ubit account
(2) Enter groups dashboard to view groups
(3) Enter a group
(4) Add/Remove users to and from desired groups
