### ISSUE TITLE
Task: Connect backend to mysql provided from the instructor

### ISSUE THREAD

**Issue by snahcuub** [cse442-fall-2019-offering/442projects-django-mango#65]
1. Go to the backend project folder in the directory /442projects-django-mango/backend/backend
2. Modify DATABASES in the file settings.py from sqlite3 to mysql:
3. Add the following to under DATABSES:
"default": {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'cse442_542_2019_fall_teamd_db'
        'USER': '<user_name of the user',
        'PASSWORD': '<password of the user',
        'HOST': 'tethys.cse.buffalo.edu',
        'PORT': '3306',
    }
4. Go back one directory by running "cd .."
5. Run the command "python manage.py migrate"

**Comment by bryanamoy** [comment]
Task Test:
(1) enter backend directory
(2) run <i>python manage.py test<i>
