### ISSUE TITLE
Group Creation

### ISSUE THREAD

**Issue by DannySager** [cse442-fall-2019-offering/442projects-django-mango#8]
As a student who has not found a group that fits my needs but want to present my ideas for other students to see I want to create my own group so that others with similar ideas can join.

**Comment by DannySager** [comment]
Snahcuub, please write tasks for your section
-Luke

**Comment by bryanamoy** [comment]
Acceptance Test:
(1)Enter website as user
(2)Set preferred languages
(3)Check if group assigned if related to preferences
