### ISSUE TITLE
Group creation preferences

### ISSUE THREAD

**Issue by DannySager** [cse442-fall-2019-offering/442projects-django-mango#9]
As a student who is creating their own group I want to list the specifics about what programming languages, project idea and more so I use the tools provided to list this information to other students.

**Comment by bryanamoy** [comment]
Acceptance Test:
(1) Click Create a Group Button
(2) Be able to enter user's name and group name in text fields
(3) Be able to select group's programming language preferences from the drop down menu

**Comment by bryanamoy** [comment]
Write Tasks Luke
